# Generated by Django 5.0 on 2024-01-04 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleID', models.IntegerField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=50)),
                ('Description', models.CharField(blank=True, help_text='Description of the role and its permisions', max_length=50)),
            ],
            options={
                'db_table': 'Role',
                'db_table_comment': 'Role and Permissions Table',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(help_text='Auto Incremented ID for the user', primary_key=True, serialize=False)),
                ('DateCreated', models.DateTimeField(auto_now_add=True, help_text='Date of creation of the user')),
                ('UserID', models.IntegerField(editable=False, help_text='Unique ID for the user', unique=True)),
                ('Name', models.CharField(help_text='Name of the user', max_length=50)),
                ('Email', models.EmailField(help_text='Email of the user', max_length=254)),
                ('Password', models.CharField(help_text=' Password of the user')),
                ('Address', models.CharField(help_text='Address of the user', max_length=50)),
                ('Role_id', models.ForeignKey(default=2, help_text='Role and perms of the user as defined from ROLE table BY DEAFULT= 2 [STUDENT]', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.role')),
            ],
            options={
                'db_table': 'Users',
                'db_table_comment': 'Reegistered User  information Table',
                'ordering': ['DateCreated'],
            },
        ),
    ]
