# Generated by Django 5.0.1 on 2024-01-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="Email",
            field=models.EmailField(
                help_text="Email of the user", max_length=254, unique=True
            ),
        ),
    ]
