# Generated by Django 5.0.2 on 2024-03-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.tags'),
        ),
    ]
