# Generated by Django 5.0.1 on 2024-01-21 10:10

import api.users.user_models.user_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=api.users.user_models.user_model.Users.get_profile_pic_filename),
        ),
    ]
