# Generated by Django 5.0.1 on 2024-02-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tags',
            table='Tags',
        ),
    ]
