# Generated by Django 5.0.1 on 2024-02-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_users_school_id_alter_users_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(
                max_length=254, primary_key=True, serialize=False, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="id",
            field=models.IntegerField(unique=True),
        ),
    ]
