# Generated by Django 5.0.2 on 2024-03-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_resources_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
