# Generated by Django 5.0 on 2024-01-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserID',
            field=models.IntegerField(help_text='Unique ID for the user'),
        ),
    ]
