# Generated by Django 5.0.1 on 2024-01-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["DateCreated"]},
        ),
        migrations.AlterModelTableComment(
            name="user",
            table_comment="Reegistered User  information Table",
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="user",
            name="password",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.AlterField(
            model_name="user",
            name="Email",
            field=models.EmailField(help_text="Email of the user", max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="UserID",
            field=models.IntegerField(
                help_text="Unique User ID assogned to user for ideentifiacations"
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table="Users",
        ),
    ]
