# Generated by Django 5.0.1 on 2024-02-28 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tags_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresourceinteraction',
            name='dislikes',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='userresourceinteraction',
            name='likes',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='userresourceinteraction',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
