# Generated by Django 5.0.1 on 2024-02-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_users_email_alter_users_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="users",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
