# Generated by Django 5.0.2 on 2024-02-29 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userresourceinteraction_dislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresourceinteraction',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='userresourceinteraction',
            name='downloaded',
        ),
        migrations.RemoveField(
            model_name='userresourceinteraction',
            name='likes',
        ),
    ]
