# Generated by Django 5.0.1 on 2024-01-18 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_users_alter_user_table_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="_id",
            new_name="ID",
        ),
    ]
