# Generated by Django 5.0.2 on 2024-03-09 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_resources_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
