# Generated by Django 5.0 on 2024-01-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_user_userid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="UserID",
            field=models.UUIDField(
                help_text="Unique User ID assogned to user for ideentifiacations"
            ),
        ),
    ]
