# Generated by Django 5.0.1 on 2024-02-27 07:01

import api.users.user_models.user_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_users_email_alter_users_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="profile_pic",
            field=models.ImageField(
                default="/upload/profile_pic/default/Default-Profile-Picture-Transparent-Image.png",
                upload_to=api.users.user_models.user_model.Users.get_profile_pic_filename,
            ),
        ),
    ]
