# Generated by Django 5.0.2 on 2024-03-01 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userresourceinteraction_resource_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresourceinteraction',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
