# Generated by Django 5.0.1 on 2024-01-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename__id_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='school_id',
            field=models.IntegerField(unique=True),
        ),
    ]
