# Generated by Django 5.0 on 2024-01-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_user_userid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ID",
            field=models.IntegerField(
                help_text="Auto Incremented ID for the user",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
