# Generated by Django 5.0.1 on 2024-02-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_users_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=16, verbose_name="password"),
        ),
    ]
