# Generated by Django 5.0.1 on 2024-02-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_users_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=255, verbose_name="password"),
        ),
    ]
