# Generated by Django 5.0.1 on 2024-01-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_users_school_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='userid',
        ),
        migrations.AlterField(
            model_name='users',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
