# Generated by Django 5.0 on 2024-01-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserID',
            field=models.IntegerField(help_text='Unique User ID assogned to user for ideentifiacations'),
        ),
    ]
