# Generated by Django 5.0.2 on 2024-03-01 07:35

import api.resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userresourceinteraction_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_image',
            field=models.ImageField(blank=True, default='upload/resource_image/default_book.png', null=True, upload_to=api.resources.models.Resources.get_resources_filename),
        ),
    ]
