# Generated by Django 5.0 on 2024-01-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_user_userid"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExampleMolde",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ExampleField", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "ExampleTable",
                "db_table_comment": "ExampleTable",
            },
        ),
    ]
