# Generated by Django 5.0.1 on 2024-01-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_users_groups_users_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['date_joined'], 'verbose_name': 'users'},
        ),
        migrations.AlterField(
            model_name='users',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
