# Generated by Django 5.0.1 on 2024-01-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_users_options_alter_users_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_permissions',
        ),
    ]
