# Generated by Django 5.0.1 on 2024-01-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_users_groups_remove_users_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='api_users',
        ),
    ]
