# Generated by Django 5.0.1 on 2024-01-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_users_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['ID'], 'verbose_name': 'users'},
        ),
    ]
