# Generated by Django 5.0.1 on 2024-01-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_users_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['date_joined'], 'verbose_name': 'users'},
        ),
    ]
